-- Generated by Oracle SQL Developer REST Data Services 22.2.0.173.2018
-- Exported REST Definitions from ORDS Schema Version 23.4.0.r3461619
-- Schema: IOT   Date: Wed Dec 27 11:04:37 CET 2023
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'IOT',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'iot',
      p_auto_rest_auth      => FALSE);    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'iotv1',
      p_base_path      => '/iotv1/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'currentsetting/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'currentsetting/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select groupname,lowtemp,hightemp,selectedtemp,nvl(adjusted_low,lowtemp)adjustedtemp,nvl(backupsensor,0) backupsensor from tempgroups'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'groupconfig/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'groupconfig/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select groupid,groupname,inuse,sensortype,sensorconfig,usetermostat,lowtemp,hightemp,backupsensor from tempgroups'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'groupconfigall',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'groupconfigall',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select groupid,groupname,inuse,sensortype,sensorconfig,usetermostat,lowtemp,hightemp,selectedtemp from tempgroups'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'iotstats/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'iotstats/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select willfail,l.logname name,l.logvalue value,l.logtime logtime from iotlogs  l where l.siteid=:siteid and l.logtime = (select max(l2.logtime) from iotlogs l2 where l2.logname = l.logname)'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'iotstats/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'declare
  id iotlogs.id%type;
BEGIN
  INSERT INTO iotlogs(logname, logtime, siteid, logvalue)
     VALUES (:logname,sysdate,:siteid,:logvalue)
  RETURNING ID INTO id;
  :status := 201;
END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'iotstats/:siteid',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'iotstats/:siteid',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select l.logname name,l.logvalue value,to_char(l.logtime+1/24,''DD/mm-yy hh24:mi:ss'') logtime from iotlogs  l where l.siteid=:siteid and l.logtime = (select max(l2.logtime) from iotlogs l2 where l2.logname = l.logname
  and l2.logtime>(sysdate-(to_number(to_char(sysdate,''hh24''))/24)) )'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'members/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'members/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select t.groupname,m.membername from tempgroups t,tempgroupmembers m where m.groupid=t.groupid'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'setrange/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'setrange/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin setrange(:groupname,:lowtemp,:hightemp,:p_status);commit; end;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'setrange/',
      p_method             => 'POST',
      p_name               => 'groupname',
      p_bind_variable_name => 'groupname',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'setrange/',
      p_method             => 'POST',
      p_name               => 'hightemp',
      p_bind_variable_name => 'hightemp',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'setrange/',
      p_method             => 'POST',
      p_name               => 'lowtemp',
      p_bind_variable_name => 'lowtemp',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'setrange/',
      p_method             => 'POST',
      p_name               => 'sqlstatus',
      p_bind_variable_name => 'p_status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'settemp/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'settemp/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin settemp(:groupid,:selectedtemp,:p_status);commit; end;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'settemp/',
      p_method             => 'POST',
      p_name               => 'groupid',
      p_bind_variable_name => 'groupid',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'settemp/',
      p_method             => 'POST',
      p_name               => 'selectedtemp',
      p_bind_variable_name => 'selectedtemp',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'settemp/',
      p_method             => 'POST',
      p_name               => 'sqlstatus',
      p_bind_variable_name => 'p_status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'settempbyname/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'settempbyname/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin settempbyname(:groupname,:selectedtemp,:p_status);commit; end;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'settempbyname/',
      p_method             => 'POST',
      p_name               => 'groupname',
      p_bind_variable_name => 'groupname',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'settempbyname/',
      p_method             => 'POST',
      p_name               => 'selectedtemp',
      p_bind_variable_name => 'selectedtemp',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'settempbyname/',
      p_method             => 'POST',
      p_name               => 'sqlstatus',
      p_bind_variable_name => 'p_status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);      


  COMMIT; 
END;