-- Generated by Oracle SQL Developer REST Data Services 19.2.1.247.2212
-- Exported REST Definitions from ORDS Schema Version 19.2.0.r1991647
-- Schema: IOT   Date: Sat Jul 04 09:01:29 CEST 2020
--
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'IOT',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'iot',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => '3l',
      p_base_path      => '/3l/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => '3l',
      p_pattern        => 'groupconfig3l',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => '3l',
      p_pattern        => 'groupconfig3l',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select groupname,lowtemp low,hightemp high,selectedtemp, ''-->''||user||''<--'' ordsuser from tempgroups'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'iotv1',
      p_base_path      => '/iotv1/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'currentsetting/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'currentsetting/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select groupname,lowtemp,hightemp,selectedtemp from tempgroups'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'groupconfig/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'groupconfig/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select groupid,groupname,inuse,sensortype,sensorconfig from tempgroups'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'iotstats/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'iotstats/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'declare
  id iotlogs.id%type;
BEGIN
  INSERT INTO iotlogs(logname, logtime, siteid, logvalue)
     VALUES (:logname,sysdate,:siteid,:logvalue)
  RETURNING ID INTO id;
  :status := 201;
END;'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'iotstats/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select l.logname name,l.logvalue value,l.logtime logtime from iotlogs  l where l.siteid=:siteid and l.logtime = (select max(l2.logtime) from iotlogs l2 where l2.logname = l.logname)'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'iotstats/:siteid',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'iotstats/:siteid',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select l.logname name,l.logvalue value,l.logtime logtime from iotlogs  l where l.siteid=:siteid and l.logtime = (select max(l2.logtime) from iotlogs l2 where l2.logname = l.logname)'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'members/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'members/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select t.groupname,m.membername from tempgroups t,tempgroupmembers m where m.groupid=t.groupid'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'settemp/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'settemp/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin settemp(:groupid,:selectedtemp,:p_status);commit; end;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'settemp/',
      p_method             => 'POST',
      p_name               => 'groupid',
      p_bind_variable_name => 'groupid',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'settemp/',
      p_method             => 'POST',
      p_name               => 'selectedtemp',
      p_bind_variable_name => 'selectedtemp',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'settemp/',
      p_method             => 'POST',
      p_name               => 'sqlstatus',
      p_bind_variable_name => 'p_status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);      

  ORDS.DEFINE_MODULE(
      p_module_name    => 'iotv1o',
      p_base_path      => '/iotv1o/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1o',
      p_pattern        => 'groupconfigo/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1o',
      p_pattern        => 'groupconfigo/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select groupname,lowtemp low,hightemp high,selectedtemp, ''-->''||:user||''<--'' ordsuser from tempgroups'
      );

  ORDS.DEFINE_MODULE(
      p_module_name    => 'iotv1p',
      p_base_path      => '/iotv1p/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1p',
      p_pattern        => 'groupconfigp/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1p',
      p_pattern        => 'groupconfigp/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select groupname,lowtemp low,hightemp high,selectedtemp, ''-->''||:current_user||''<--'' ordsuser from tempgroups'
      );

  ORDS.CREATE_ROLE(p_role_name  => '3lrole');
  ORDS.CREATE_ROLE(p_role_name  => 'iotv1orole');
  ORDS.CREATE_ROLE(p_role_name  => 'iotv1role');

  l_roles(1)   := '3lrole';
  l_modules(1) := '3l';
  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'iot3l',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => '',
      p_description    => '',
      p_comments       => NULL);      
  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;

  l_roles(1)   := 'iotv1orole';
  l_modules(1) := 'iotv1o';
  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'iotv1opriv',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => '',
      p_description    => '',
      p_comments       => NULL);      
  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;

  l_roles(1)   := 'iotv1role';
  l_modules(1) := 'iotv1p';
  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'iotv1priv',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'iotv1priv',
      p_description    => 'iotv1priv',
      p_comments       => NULL);      


  COMMIT; 

END;

begin
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'iotv1',
      p_pattern        => 'settempbyname/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'iotv1',
      p_pattern        => 'settempbyname/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin settempbyname(:groupname,:selectedtemp,:p_status);commit; end;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'settempbyname/',
      p_method             => 'POST',
      p_name               => 'groupname',
      p_bind_variable_name => 'groupname',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'settempbyname/',
      p_method             => 'POST',
      p_name               => 'selectedtemp',
      p_bind_variable_name => 'selectedtemp',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'iotv1',
      p_pattern            => 'settempbyname/',
      p_method             => 'POST',
      p_name               => 'sqlstatus',
      p_bind_variable_name => 'p_status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL); 
end;	  
/
commit;